services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_render.py
    plan: free
    autoDeploy: false
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health